### ISSUE TITLE
人形升级经验

### ISSUE THREAD

**Issue by chesha1** [Therhokar/exilium#2]
经验是不是被算少了，比如44级升45级要20000经验，网站上才显示2000

**Comment by Therhokar** [comment]
其实是9月四测的时候我把项目转到Gitee了，这边后来就没更，我现在在考虑要不要把这边的归档了。
你访问GitHub Pages会更方便吗？会的话我就还是留着，然后每次同步更新就行。

**Comment by chesha1** [comment]
我其实访问哪边都行，这个无所谓
gitee我记得有功能是可以把代码自动同步push到github的，这个功能开一下就行，麻烦了
